name: CD - Publish to npm

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Publish Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Use CI Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node16-

      - name: Install 🔧
        run: npm install

      - name: Build 🏗️
        run: npm run build

      - name: Publish 📡
        id: publish
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"